pipeline {
    agent any
    
    triggers {
        githubPush()
    }
    
    stages {
        stage('Build') {
            steps {
                script {
                    docker.build('yash1133/inc42:go-1')
                }
            }
        }
        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withCredentials([usernameColonPassword(credentialsId: '7e62c798-7ac1-46a1-ba99-d5f2272b44c7', variable: 'docker')]) {
                        docker.image('yash1133/inc42:go-1').push('latest')
                    }
                }
            }
        }
        stage('Deploy to Localhost') {
            steps {
                script {
                    docker.withRegistry('', 'dockerhub_credentials') {
                        docker.image('yash1133/inc42:go-1').run('-p 9090:8080 --name hello-world-container')
                    }
                }
            }
        }
    }    
}
